export const EventTypes = {
    AUTHENTICATE: 'authenticate',
    NOTIFY: 'notify',
    DISCONNECT: 'disconnect',
    CREATE_NEW_GAME: 'CREATE_NEW_GAME',
    RECEIVE_NEW_GAME_SESSION: 'RECEIVE_NEW_GAME_SESSION',
    NEXT_LEVEL_GAME: 'NEXT_LEVEL_GAME',
    END_SESSION_GAME: 'END_SESSION_GAME',
    ON_CHOOSE_CELL: 'ON_CHOOSE_CELL',
};
