version: '3'

services:
    # cache:
    #     image: redis:alpine
    #     restart: always
    #     ports:
    #         - '6379:6379'
    game-be:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '1201:1201'
        # depends_on:
        #     - cache
        # environment:
        #     - CACHE_HOST=cache
        #     - CACHE_PORT=6379
