import { Achievement } from "../models/achievement.model";

export const achievementList: Achievement[] = [
    {
        type: 0,
        name: 'Connect your account to Discord',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 1,
        name: 'Play game in GDSC Game once',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 2,
        name: 'PReach level 10 in GDSC Quiz',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 3,
        name: 'Reach level 50 in GDSC Quiz',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 4,
        name: 'Reach level 100 in GDSC Quiz',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 5,
        name: 'Place a Bid',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 6,
        name: 'Win a Bid',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 7,
        name: 'Win 10 Bids',
        GCoin: 2000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 8,
        name: 'Clear a Daily Earning',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 9,
        name: 'Clear Daily Earnings 1 week in a row',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 10,
        name: 'Clear Daily Earnings 1 week in a row',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 11,
        name: 'Get first place in GDSC Quiz Leaderboard',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 12,
        name: 'Lose GDSC Quiz on the first stage',
        GCoin: 4000,
        target: 1,
        hidden: true,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 13,
        name: '/streak reaches 5',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 5,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 14,
        name: '/streak reaches 20',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 15,
        name: '/streak reaches 50',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 16,
        name: '/streak reaches 100',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 17,
        name: 'Use /rps, /hangman, /guess and win 3 times',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 5,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 18,
        name: 'Use /rps, /hangman, /guess and win 10 times',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 19,
        name: 'Use /rps, /hangman, /guess and win 50 times',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 20,
        name: 'Use /rps, /hangman, /guess and win 100 times',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 21,
        name: 'Use /work once',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 5,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 22,
        name: 'Use /work 20 times',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 23,
        name: 'Use /work 50 times',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 24,
        name: 'Use /work more than 15 times in one day',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 25,
        name: 'Lose 5000 GCoin or more in 1 battle',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 5,
        arena: 'Discord',
        limit: 0,
    },
    {
        type: 25,
        name: 'Win in 1 turn in /hangman or /guess',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Discord',
        limit: 0,
    },
];
