import { Achievement } from "../models/achievement.model";

export const achievementList: Achievement[] = [
    {
        type: 0,
        name: 'Connect your account to Discord',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 1,
        name: 'Play game in GDSC Game once',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 2,
        name: 'PReach level 10 in GDSC Quiz',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 3,
        name: 'Reach level 50 in GDSC Quiz',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 4,
        name: 'Reach level 100 in GDSC Quiz',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 5,
        name: 'Place a Bid',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 6,
        name: 'Win a Bid',
        GCoin: 500,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 7,
        name: 'Win 10 Bids',
        GCoin: 2000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 8,
        name: 'Clear a Daily Earning',
        GCoin: 100,
        target: 1,
        hidden: false,
        point: 10,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 9,
        name: 'Clear Daily Earnings 1 week in a row',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 10,
        name: 'Clear Daily Earnings 1 week in a row',
        GCoin: 4000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 11,
        name: 'Get first place in GDSC Quiz Leaderboard',
        GCoin: 1000,
        target: 1,
        hidden: false,
        point: 40,
        arena: 'Web game',
        limit: 0,
    },
    {
        type: 12,
        name: 'Lose GDSC Quiz on the first stage',
        GCoin: 4000,
        target: 1,
        hidden: true,
        point: 20,
        arena: 'Web game',
        limit: 0,
    },
];
